#
# https://starship.rs/
#

# Use custom format
format = """$directory$all
$character"""
#right_format = """$time$cmd_duration$battery"""

# # Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
#
# # Disable the blank line at the start of the prompt
#add_newline = false

[character]
success_symbol =  "[](bold green)"
error_symbol =    "[](bold red)"
vicmd_symbol =    "[ ](bold fg:3)"

[directory]
format = '[ $path ]($style)($read_only_style)'
style = "bold cyan"
truncation_length = 12
truncation_symbol = "…/"
read_only_style = ""

# [time]
# disabled = false
# format = '[\[$time\]](green)'
# time_format = "%T"

[cmd_duration]
format = "[ $duration](cyan)"

# [battery]
# disabled = false
# format = "[ $symbol$percentage](red) "

# [[battery.display]]
# threshold = 30

