#
# https://starship.rs/
#

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[v](bold fg:8)"

[cmd_duration]
format = "[$duration ](fg:3)"

[directory]
truncation_length = 8
truncation_symbol = "…/"

[time]
disabled = true
format = '[\[$time\]](fg:3) '
time_format = "%T"

[battery]
charging_symbol = "⚡️"
discharging_symbol = " "

[[battery.display]]
threshold = 30
style = "bold yellow"


