# OpenWeatherMap configuration
[openweathermap]
enabled = true
api_key = "bc3aaad3c4417515925c3c0f810dbdc3"
city_id = "3465729"
notification_timeout = 10
notification_body = "Expected within the next 3 hours"
sync_frequency = 1800 # 30 minutes
# display = "{{ temp_icon }} {{ temp_celsius }}°C"
display = "{{ temp_celsius }}°C"

# GitHub configuration
[github]
enabled = true
api_key = "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"
notification_timeout = 20
show_avatar = false
sync_frequency = 900 # 15 minutes
# display = "{{ unread_count }}"
display = " {{ unread_count }}"

# MPD configuration
[mpd]
enabled = false
music_directory = "/mnt/media/music"
notification_timeout = 10
cover_name = "cover.jpg"
skip_missing_cover = true
